---
- name: Detectar SO
  debug:
    msg: "SO detectado: {{ ansible_distribution }} {{ ansible_distribution_version }}"

- import_tasks: ubuntu.yaml
  when: ansible_os_family == "Debian"

- import_tasks: sles15.yaml
  when: ansible_distribution == "SLES"

- import_tasks: opensuse_tumbleweed.yaml
  when: ansible_distribution == "openSUSE Tumbleweed"

- import_tasks: disable_swap.yaml
