- name: Instalar o Helm, Cert-Manager e rancher
  hosts: rancher_servers
  become: yes
  vars:
    rancher_hostname: "rancher.example.com"
    cert_manager_version: "v1.12.0"
  roles:
    - helm
    - cert-manager
    - rancher